baseurl: https://coliff.github.io/radium-hugo/
title: Radium
languageCode: en
locale: en-us
theme: radium
disableRSS: true
defaultContentLanguageInSubdir: true
googleAnalytics: UA-xxxxxx-xx

publishdir: "docs/"

enableRobotsTXT: true

disableKinds: ["taxonomy", "taxonomyTerm", "category", "RSS"]

params:
  title: Radium
  description: Radium is a boilerplate for Hugo with advanced productivity-boosting features

taxonomies:
  tag: ""
  group: ""
  category: ""

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
