baseurl: https://coliff.github.io/radium-hugo/
title: Radium
languageCode: en
theme: radium
disableRSS: true
defaultContentLanguageInSubdir: true

publishdir: "docs/"

enableRobotsTXT: true

disableKinds: ["taxonomy", "taxonomyTerm", "category", "RSS"]

taxonomies:
  tag: ""
  group: ""
  category: ""

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
